### PR TITLE
Fixed width of active filter on the mobile version, closed #78

### LINKED ISSUE #78: Fixed width of active filter on the mobile version
Style issues on:
- [x] the theme-overview
- [x] the theme list pages by type
- [x] check all UI elements: the filter/dropdown/search on other pages on the mobile version

theme-overview-1
theme-overview-2

### PR DESCRIPTION
**Pull request by krausweb**
- fixed active filter style on the mobile and tablet version
- fixed the eslinter terminal error with lazy import(added babel-eslint, reorder devDependency, remove node_modules and ran clear install!)
- fixed the footer z-index style bug when small content and opened search result
- removed unnecessary the notice plugin for the CalendarPlugin
- added the API wrapper for meetings pages
- fixed the .finally bug in the IE11 and NodeJS v8
- fixed typos, minor

---

If you have an error on the Stage server with "TypeError: Cannot read property 'range' of null", there is a babel-eslint bug, need to: 
1) remove node_module and yarn.lock
2) run ./devops yarn install

### CODE REVIEW

File: resources/js/components/CalendarPlugin.vue [hunk 1]
```diff
@@ -70,21 +68,20 @@ export default {
                 el.style.pointerEvents = this.loading ? 'none' : 'auto';
             });
         },
-        loadMeetings(year = this.currentYear, month = this.currentMonth) {
+        async loadMeetings(year, month) {
```
Comment (vnchenko) [inline resources/js/components/CalendarPlugin.vue]: add error validation

File: resources/js/components/CalendarPlugin.vue [hunk 2]
```diff
@@ -70,21 +68,20 @@ export default {
...
             if (!this.loading) {
                 this.loading = true;
                 this.currentYear = year;
                 this.currentMonth = month;
 
                 this.disableEnableNavButtons();
 
-                axios
-                    .get(`/api/meetings?year=${this.currentYear}&month=${this.currentMonth}`)
+                await meeting.getMeetingsByYearAndMonth(year, month)
```
Comment (vnchenko) [inline resources/js/components/CalendarPlugin.vue]: use await or then

File: resources/js/components/CalendarPlugin.vue [hunk 3]
```diff
@@ -121,7 +117,7 @@ export default {
         },
     },
     mounted() {
```
Comment (vnchenko) [inline resources/js/components/CalendarPlugin.vue]: mb u can use created hook

File: resources/sass/components/_filters.scss [hunk 4]
```diff
@@ -78,21 +81,10 @@
         padding-bottom: $indent-m;
         padding-top: $indent-m;
         position: absolute;
-        right: auto;
-        top: calc(100% + 15px);
-        transform: translateX(-50%);
+        left: 0;
+        width: inherit;
         z-index: 101;
```
Comment (vnchenko) [inline resources/sass/components/_filters.scss]: I think, that it would be great to create singly file for z-indexes

File: resources/js/components/Meeting/MeetingList.vue [hunk 5]
```diff
@@ -23,25 +23,23 @@ export default {
...
+        async lazyHandle() {
             if (!this.loading && !this.emptyMeetingList) {
                 this.loading = true;
                 this.currentPage += 1;
                 const cardList = document.querySelector(this.cardListSelector);
 
-                axios
-                    .get('/api/meetings?page=' + this.currentPage)
+                await meeting.getMeetingList(this.currentPage)
                     .then(res => {
```
Comment (vnchenko) [inline resources/js/components/Meeting/MeetingList.vue]: the same for await and then

File: resources/sass/layouts/_footer.scss [hunk 6]
```diff
@@ -2,7 +2,7 @@
     background-color: $c-white;
     padding-top: 100px;
     position: relative;
-    z-index: 4;
+    z-index: 3;
```
Comment (vnchenko) [inline resources/sass/layouts/_footer.scss]: the same for z-index

File: resources/sass/layouts/_header.scss [hunk 7]
```diff
@@ -12,7 +12,7 @@
         box-shadow: 0 1px 6px 0 $c-box-shadow2;
         font-size: 0;
         position: relative;
-        z-index: 3;
+        z-index: 4;
```
Comment (vnchenko) [inline resources/sass/layouts/_header.scss]: the same for z-index

**Comment by krausweb** [comment]
All fixed, refactored

File: resources/sass/vendors/_v-tooltip-custom.scss [hunk 8]
```diff
@@ -16,7 +16,7 @@
         position: absolute;
         margin: 5px;
         border-color: $c-black;
-        z-index: 1;
+        z-index: 100;
```
Comment (vnchenko) [inline resources/sass/vendors/_v-tooltip-custom.scss]: replace on variable

File: resources/sass/components/_filters.scss (hunk 4 above)
Comment (vnchenko) [inline resources/sass/components/_filters.scss]: replace on variable
